# Generated by Django 2.0.2 on 2018-03-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180306_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
