# Generated by Django 2.0.2 on 2018-03-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('course_type', models.CharField(max_length=50)),
                ('grade', models.IntegerField()),
                ('department', models.CharField(max_length=20)),
                ('college', models.CharField(max_length=20)),
                ('student_limit', models.IntegerField()),
                ('student_select', models.IntegerField()),
            ],
        ),
    ]
