# Generated by Django 2.0.2 on 2018-03-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_num',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='college',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='student_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='student_select',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
