# Generated by Django 2.0.2 on 2018-03-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('credit', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('semester', models.IntegerField(default=0)),
                ('course_num', models.CharField(blank=True, max_length=20, null=True)),
                ('course_type', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.IntegerField(default=0)),
                ('department', models.CharField(blank=True, max_length=20, null=True)),
                ('college', models.CharField(blank=True, max_length=20, null=True)),
                ('student_limit', models.IntegerField(default=0)),
                ('student_select', models.IntegerField(default=0)),
            ],
        ),
    ]
