# Generated by Django 2.0.2 on 2018-03-20 07:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetemp',
            name='schooltime',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
