# Generated by Django 2.0.2 on 2018-03-21 00:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_num', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(default='匿名', max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('teacher_name', models.CharField(max_length=20)),
                ('hidden', models.BooleanField()),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.Comment')),
            ],
        ),
    ]
